export const USER_NAME_MAX_LENGTH = 64;
export const USER_USERNAME_MAX_LENGTH = 32;
export const USER_EMAIL_MAX_LENGTH = 256;

export const ORG_NAME_MAX_LENGTH = 64;
export const ORG_DESCRIPTION_MAX_LENGTH = 1024;
export const ORG_SLUG_MAX_LENGTH = 64;

export const PROJECT_NAME_MAX_LENGTH = 64;
export const PROJECT_DESCRIPTION_MAX_LENGTH = 1024;
export const PROJECT_SLUG_MAX_LENGTH = 64;

export const ISSUE_TITLE_MAX_LENGTH = 64;
export const ISSUE_DESCRIPTION_MAX_LENGTH = 2048;
export const ISSUE_TYPE_MAX_LENGTH = 16;
export const ISSUE_STATUS_MAX_LENGTH = 24;
export const ISSUE_COMMENT_MAX_LENGTH = 2048;
